'use strict';
process.env.NODE_ENV='test';
const test=require('node:test');const assert=require('node:assert/strict');const {server}=require('../server');const db=require('../lib/db');
test('单站卡片变体拥有独立参数和站点售价',async(t)=>{
  await new Promise((resolve)=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
  t.after(async()=>{await new Promise((resolve)=>server.close(resolve));await db.close()});
  const created=await (await fetch(`${base}/api/projects`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'折叠灯'})})).json();
  const projectId=created.id;
  await fetch(`${base}/api/projects/${projectId}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({cost_cny:110,length:44,width:21,height:7,dimension_unit:'cm',weight:1.37,weight_unit:'kg'})});
  await fetch(`${base}/api/projects/${projectId}/countries/AU`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({sale_price:59})});
  let variants=(await (await fetch(`${base}/api/projects/${projectId}/site-card-variants?country_code=AU`)).json()).variants;
  assert.equal(variants.length,1);assert.equal(variants[0].cost_cny,110);assert.equal(variants[0].sale_price,59);
  const rgb=await (await fetch(`${base}/api/projects/${projectId}/site-card-variants`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({copy_from:variants[0].id,name:'RGB 款'})})).json();
  await fetch(`${base}/api/site-card-variants/${rgb.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({name:'RGB 款',cost_cny:145,length:47,width:24,height:9,weight:1.65,country_code:'AU',sale_price:79})});
  variants=(await (await fetch(`${base}/api/projects/${projectId}/site-card-variants?country_code=AU`)).json()).variants;
  assert.deepEqual(variants.map((v)=>[v.name,v.cost_cny,v.sale_price]),[['默认变体',110,59],['RGB 款',145,79]]);
  const normalCalc=await (await fetch(`${base}/api/calculate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project_id:projectId,country_code:'AU',variant_id:variants[0].id})})).json();
  const rgbCalc=await (await fetch(`${base}/api/calculate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project_id:projectId,country_code:'AU',variant_id:rgb.id})})).json();
  assert.equal(normalCalc.results[0].sale_price,59);assert.equal(rgbCalc.results[0].sale_price,79);assert.equal(rgbCalc.results[0].variant_name,'RGB 款');
  assert.notEqual(normalCalc.results[0].product_cost,rgbCalc.results[0].product_cost);
  assert.notEqual(normalCalc.results[0].freight_fee,rgbCalc.results[0].freight_fee);
  const original=await (await fetch(`${base}/api/projects/${projectId}`)).json();
  assert.equal(original.cost_cny,110);assert.equal(original.listings.find(v=>v.country_code==='AU').sale_price,59);
  const invalid=await fetch(`${base}/api/site-card-variants/${rgb.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({cost_cny:-1})});assert.equal(invalid.status,400);
  const other=await (await fetch(`${base}/api/projects`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'隔离测试'})})).json();
  const mismatch=await fetch(`${base}/api/calculate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project_id:other.id,country_code:'AU',variant_id:rgb.id})});assert.equal(mismatch.status,404);
  await fetch(`${base}/api/projects/${other.id}`,{method:'DELETE'});
  const record=await (await fetch(`${base}/api/projects/${projectId}/site-card-records`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({country_code:'AU',variant_id:rgb.id,variant_name:'RGB 款',sale_price:79,cost_cny:145,snapshot:rgbCalc.results[0]})})).json();
  assert.equal(record.variant_id,rgb.id);
  const remove=await fetch(`${base}/api/site-card-variants/${rgb.id}`,{method:'DELETE'});assert.equal(remove.status,200);
  const history=(await (await fetch(`${base}/api/projects/${projectId}/site-card-records?country_code=AU`)).json()).records;
  assert.equal(history[0].variant_id,null);assert.equal(history[0].variant_name,'RGB 款');assert.equal(history[0].sale_price,79);
  await fetch(`${base}/api/projects/${projectId}`,{method:'DELETE'});
});
