BEGIN;

CREATE TABLE IF NOT EXISTS countries (
  code text PRIMARY KEY,name text NOT NULL,flag text NOT NULL,currency text NOT NULL,symbol text NOT NULL,
  cny_per_local numeric NOT NULL,vat_rate numeric NOT NULL DEFAULT 0,tax_rate numeric NOT NULL DEFAULT 0,
  tax_basis text NOT NULL DEFAULT 'none',tax_label text NOT NULL DEFAULT '税费预估',active boolean NOT NULL DEFAULT true,
  fba_volume_divisor numeric NOT NULL DEFAULT 6000,priority integer NOT NULL DEFAULT 99,
  tax_note text NOT NULL DEFAULT '',source_note text NOT NULL DEFAULT '',updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS size_tiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,country_code text NOT NULL REFERENCES countries(code),
  tier_code text NOT NULL,tier_name text NOT NULL,max_long_cm numeric NOT NULL,max_mid_cm numeric NOT NULL,
  max_short_cm numeric NOT NULL,min_item_weight_kg numeric NOT NULL DEFAULT 0,max_item_weight_kg numeric NOT NULL,
  max_volume_weight_kg numeric,max_total_cm numeric,dimension_mode text NOT NULL DEFAULT 'none',
  class_weight_mode text NOT NULL DEFAULT 'actual',fee_weight_mode text NOT NULL DEFAULT 'max',
  status text NOT NULL DEFAULT 'verified',source_note text NOT NULL DEFAULT '',UNIQUE(country_code,tier_code)
);

CREATE TABLE IF NOT EXISTS fba_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,country_code text NOT NULL REFERENCES countries(code),
  size_name text NOT NULL,max_long_cm numeric NOT NULL,max_mid_cm numeric NOT NULL,max_short_cm numeric NOT NULL,
  max_weight_kg numeric NOT NULL,max_total_cm numeric,included_weight_kg numeric NOT NULL DEFAULT 0,
  base_fee numeric NOT NULL,per_kg_fee numeric NOT NULL DEFAULT 0,surcharge_rate numeric NOT NULL DEFAULT 0,
  weight_increment_kg numeric NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'estimate',source_note text NOT NULL DEFAULT '',
  size_tier text NOT NULL DEFAULT '',min_price numeric,max_price numeric,category_group text NOT NULL DEFAULT 'all'
);

CREATE TABLE IF NOT EXISTS freight_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,country_code text NOT NULL UNIQUE REFERENCES countries(code),
  channel_name text NOT NULL DEFAULT '默认渠道',price_per_kg_cny numeric NOT NULL DEFAULT 0,
  pricing_mode text NOT NULL DEFAULT 'kg',price_per_cbm_cny numeric NOT NULL DEFAULT 0,
  min_charge_cny numeric NOT NULL DEFAULT 0,volume_divisor numeric NOT NULL DEFAULT 6000,
  status text NOT NULL DEFAULT 'missing',source_note text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS commission_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,country_code text NOT NULL REFERENCES countries(code),
  parent_category text NOT NULL,keywords text NOT NULL,rate numeric NOT NULL,min_price numeric,max_price numeric,
  threshold_price numeric,rate_above numeric,minimum_fee numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'estimate',source_note text NOT NULL DEFAULT ''
);

-- 仅供本地联调和数据契约示例。生产环境建议将下方视图改为直接 SELECT 公司现有表。
CREATE TABLE IF NOT EXISTS dashboard_product_sites_source (
  asin text NOT NULL,owner_name text NOT NULL,product_name text,image_url text,
  length_cm numeric,width_cm numeric,height_cm numeric,weight_kg numeric,cost_cny numeric,
  country_code text NOT NULL,sale_price numeric,category_text text,referral_rate_override numeric,
  declaration_ratio numeric,declared_value_override numeric,customs_rate numeric,consumption_tax_rate numeric,
  PRIMARY KEY (asin,country_code)
);

DROP VIEW IF EXISTS dashboard_product_sites_v;
CREATE VIEW dashboard_product_sites_v AS
SELECT asin,owner_name,product_name,image_url,length_cm,width_cm,height_cm,weight_kg,cost_cny,
       country_code,sale_price,category_text,referral_rate_override,declaration_ratio,
       declared_value_override,customs_rate,consumption_tax_rate
FROM dashboard_product_sites_source;

CREATE INDEX IF NOT EXISTS idx_dashboard_source_owner ON dashboard_product_sites_source(owner_name);
CREATE INDEX IF NOT EXISTS idx_dashboard_source_asin ON dashboard_product_sites_source(asin);

COMMIT;
